### ISSUE TITLE
Write an ADR about secret management with Vault

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/dev-rel-docs#117]
Create follow issue to turn this into an ADR to review by team and security.

_Originally posted by @rngadam in https://github.com/ai-cfia/howard/pull/65#discussion_r1533900430_
            
We have decided to establish our infrastructure with the use of Hasicorp Vault as a secret manager instead of solutions like Azure Key Vault or Github secrets. We would like to have this ADR documented here.

**Comment by rngadam** [comment]
@SonOfLope no projects set

**Comment by SonOfLope** [comment]
Closed in https://github.com/ai-cfia/dev-rel-docs/pull/86
