### ISSUE TITLE
Write an ADR to explain how images are managed inside this organisation

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/dev-rel-docs#90]
- Explain how we manage docker images inside the organisation

**Comment by rngadam** [comment]
What kind of images? Nachet microscope images or Docker images? Because we actually need to work on the design of both.

**Comment by ThomasCardin** [comment]
> What kind of images? Nachet microscope images or Docker images? Because we actually need to work on the design of both.

Don't you read issue description?

**Comment by ThomasCardin** [comment]
Wil be done via this issue: https://github.com/ai-cfia/dev-rel-docs/issues/124
