### ISSUE TITLE
Document Design Philosophy and UX Concept

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/dev-rel-docs#91]
### Task Description
Develop a comprehensive document that outlines the Design Philosophy and UX Concept, which will serve as a guideline for current and future projects. This document will be a part of the `dev-rel-docs` repository.

### Objectives
- Clearly articulate the User-Centric Design approach, underlining its significance in creating intuitive and user-friendly interfaces.
- Define the Overall User Experience Goal to establish a benchmark for efficient and streamlined user interactions across projects.
- Enumerate the generic UX and UI principles that are fundamental to frontend component design, emphasizing consistency, accessibility, and performance optimization.

### Acceptance Criteria
- The document should provide a clear and comprehensive description of the design philosophy and UX concept.
- Include detailed sections on:
  - User-Centric Design
  - Overall User Experience Goal
  - Generic UX and UI Principles for Frontend Components
- The content should be engaging, informative, and cater to both technical and non-technical stakeholders.

**Comment by rngadam** [comment]
reference https://www.canada.ca/en/government/system/digital-government/government-canada-digital-standards.html "Design with Users" and other related UX tenets.
